sudo: required
dist: trusty
language: cpp
os:
- linux
compiler:
- gcc
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - lcov
before_script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./misc/install_linux; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./misc/install_osx; fi
- chmod +x misc/checkstyle.sh
- cmake . -DCMAKE_BUILD_TYPE=debug -DCMAKE_VERBOSE_MAKEFILE=true
script:
- make native_test -j8
- ./misc/memory_check
- make native && sudo make install && sudo ldconfig
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd examples && ./build; fi
after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
notifications:
  slack: foodtiny:hzkLBCLrqjtgi9ctqwdQ034S
