sudo: required
language: c
os:
- linux
- osx
compiler:
- gcc
before_script:
- apt-get install software-properties-common
- add-apt-repository ppa:george-edison55/cmake-3.x
- apt-get update
- apt-get upgrade
- cmake .
script:
- make native
- ./native