sudo: required
dist: trusty
language: cpp
os:
- linux
compiler:
- gcc
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - lcov
before_script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./misc/install_linux; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./misc/install_osx; fi
- chmod +x misc/checkstyle.sh
- cmake . -DCMAKE_BUILD_TYPE=debug -DCMAKE_VERBOSE_MAKEFILE=true
script:
- make native_test -j8
- ./misc/memory_check
- make native && sudo make install && sudo ldconfig
- cd examples && ./build
after_success:
- ./misc/codecov.sh
notifications:
  slack: foodtiny:hzkLBCLrqjtgi9ctqwdQ034S
