sudo: required
dist: trusty
language: c
os:
- linux
- osx
compiler:
- gcc
before_script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./install_linux; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./install_osx; fi
- cmake .
script:
- make native
- ./native