sudo: required
language: c
os:
- linux
- osx
compiler:
- gcc
before_script:
- sudo apt-get install software-properties-common
- sudo add-apt-repository ppa:george-edison55/cmake-3.x
- sudo apt-get update
- sudo apt-get upgrade
- cmake .
script:
- make native
- ./native